### ISSUE TITLE
Browser notification for chapter change?

### ISSUE THREAD

**Issue by switz** [aalexeenco/YouTubeChapters#132]
Sometimes I watch long videos and would love to get a native notification when the chapter changes. How hard would this be to implement?

**Comment by aalexeenco** [comment]
It shouldn't be hard, I will add extension options to show native notifications on chapter change. 

By default notification will not be shown, enable them in the Extension -> Details -> Extension Options.

**Comment by aalexeenco** [comment]
Fixed in v3.0.0.
